#@ load("@ytt:data", "data")

apiVersion: v1
kind: Secret
metadata:
  name: azure-open-ai-secret
  namespace: acme-fitness
type: Opaque
stringData:
  key: #@ data.values.openai.key
  endpoint: #@ data.values.openai.endpoint